### ISSUE TITLE
Stop Command Not Functioning

### ISSUE THREAD

**Issue by ryancasler** [vervallsweg/cast-web-api-cli#4]
When I use the stop command, I am getting an error response from the API.  Any idea what I'm doing wrong?

dev:25332019-06-12 10:31:41.041 pm errorjson response not ok: [response:error, error:[:]]

**Comment by vervallsweg** [comment]
What exactly is the command you're issuing?

**Comment by ryancasler** [comment]
From the DTH, i'm just using "STOP".  It looks like it's using:

`    apiCall('/stop', true);`

**Comment by ryancasler** [comment]
Any news on this?

**Comment by ryancasler** [comment]
Dunno what changed but it started working again.
